apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdu-uct-analiz.fullname" . }}
  labels:
    {{- include "sdu-uct-analiz.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "sdu-uct-analiz.appSelectorLabels" . | nindent 4 }}
