SELECT
    kato,
    district,
    settlement,
    latitude,
    longitude,
    population,
    coverage,
    beeline,
    kcell,
    tele2,
    tower_count,
    tower_height,
    tower_coordinates,
    tower_holder,
    tower_funding,
    tower_cost,
    tower_power,
    fiber,
    satellite,
    plan,
    provider,
    potential,
    operator_count,
    four_g_count,
    broadband,
    appeals,
    is_problem,
    critical_risk,
    problem_appeals,
    problem,
    problem_operator,
    recommendation,
    risk_score,
    risk_level
FROM gold.connectivity_points
WHERE latitude BETWEEN 45 AND 55
  AND longitude BETWEEN 50 AND 65
ORDER BY risk_score DESC;
